### ISSUE TITLE
pod try Shiny fails

### ISSUE THREAD

**Issue by ghv** [efremidze/Shiny#3]
> pod try Shiny
> Updating spec repositories
> [!] Unable to find a specification for `Shiny`

**Comment by efremidze** [comment]
You might have to pull the latest spec.

Try this:
```
pod setup
pod try Shiny
```

**Comment by hemangshah** [comment]
Instead of `pod setup`, it will be more convenient to command: `pod repo update`

**Comment by efremidze** [comment]
Thanks @hemangshah

**Comment by ghv** [comment]
Thanks @hemangshah and @efremidze that did the trick for me.
