### ISSUE TITLE
Can Shiny be used with UIButtons??

### ISSUE THREAD

**Issue by sdevo619** [efremidze/Shiny#6]
This looks really cool and was considering trying to use it with one of my projects, however I was wondering if this can also be used with a UIButton or only a UIView??

**Comment by efremidze** [comment]
You can subclass it. Override [Touch Gestures](https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/handling_touches_in_your_view) to make it into a button.

I can also add button support.
